#ifndef OPTION_H
#define OPTION_H

enum class Option { 
 LOAD_DATA,
 STOP_CRITERION,
 BRUTE_FORCE,
 DEFINE_NEIGHBOR_TS,
 RUN_TABU_SEARCH,
 SET_TEMP_CHANGE_FACTOR,
 RUN_SIMULATED_ANNEALING,
 SAVE_TO_FILE,
 LOAD_COST_TABELS,
 EXIT,
 INVALID_INPUT
};
#endif
